### ISSUE TITLE
Create `FeaturedRecipe` component

### ISSUE THREAD

**Issue by ruzicic** [MonikkaKindaCodes/Healthy-Kinda-App#6]
Note: Task depends on https://github.com/edgeston/Healthy-Kinda-App/issues/5

## Todo
Create a Featured Recipe Component
- [ ] Make it responsive (mobile-first)
- [ ] Add a hover state (e.g. underline text, zoom image background)
- [ ] Add a story for the component (examples here: https://storybook.js.org/showcase/), include multiple variants: mobile, tablet, desktop

### Requirements

```ts
interface FeaturedRecipeProps {
  imageUrl: string // https://image.path.com/img.jpg
  rating: number // 4
  totalTime: string // 25 minutes
  label: string // popular
  onClick: () => void
}
```

### Design
![Screenshot 2022-08-03 at 21 38 33](https://user-images.githubusercontent.com/15891813/182695346-3c3a7fd8-0fef-4a46-bec6-3767d931a327.png)
